Fix the Deployment configs page
Hydrospheredata/hydro-serving-ui pull request #333
Opened 2021-04-13 15:19 UTC by Guzel738

- "Create Config" button works when list of deployment configs is empty;
- Adding and removing the deployment config now work correctly;
- If backend returns error, snackbar with error message is shown;
- Added guard to deployment's page, when url has wrong deployment's name guard redirects to first element or shows empty page.

2021-04-13 15:32 UTC, Vixtir requested changes

2021-04-13 15:32 UTC, Vixtir commented on src/app/modules/deployment-configs/pages/deployment-configs-page/deployment-configs-page.component.html
> -  <div class="deployment-config-page__sidebar" hsHideInZenMode>
Why did you delete it?

2021-04-13 15:38 UTC, Guzel738 commented on src/app/modules/deployment-configs/pages/deployment-configs-page/deployment-configs-page.component.html
> -  <div class="deployment-config-page__sidebar" hsHideInZenMode>
Sorry, my mistake

2021-04-13 15:58 UTC, Vixtir submitted a review, later dismissed

2021-04-13 19:01 UTC, akastav commented
Fetch from master branch new jenkinsfile and build make success

2021-04-19 08:23 UTC, Vixtir approved these changes

2021-04-19 08:23 UTC, merged